/* ******************************************************************************************************************
   * Authors:   SanAndreasP
   * Copyright: SanAndreasP
   * License:   Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
   *                http://creativecommons.org/licenses/by-nc-sa/4.0/
   *******************************************************************************************************************/
package de.sanandrew.mods.immersivecables.util;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = ICConstants.ID, name = ICConstants.NAME, version = ICConstants.VERSION, dependencies = ICConstants.DEPENDENCIES, guiFactory = ImmersiveCables.GUI_FACTORY)
public class ImmersiveCables
{
    static final String GUI_FACTORY = "de.sanandrew.mods.immersivecables.client.util.ICGuiFactory";

    @Mod.Instance(ICConstants.ID)
    public static ImmersiveCables instance;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;

        ICConfiguration.initialize(event);
    }
}
